version: '2'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:5000"
        volumes:
            - .:/app
        depends_on:
            - redis
    redis:
        image: redis